'use client';

import { useEffect, useState } from 'react';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  'https://srhopbavlugxfkdffhpa.supabase.co',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyaG9wYmF2bHVneGZrZGZmaHBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MzI2MjksImV4cCI6MjA2MDEwODYyOX0.hV78EsizxjtdrvOgwqh0eNDljkpfwaYM01PwcUFK46k'
    );

    export default function Home() {
      const [password, setPassword] = useState('');
        const [error, setError] = useState('');

          useEffect(() => {
              fetch('https://ipinfo.io/json?token=6ff95514eb5eaf')
                    .then((res) => res.json())
                          .then(async (data) => {
                                  const { ip, city, region, country, loc, org, postal, timezone } = data;
                                          const userAgent = navigator.userAgent;

                                                  await supabase.from('visitors').insert([
                                                            {
                                                                        ip,
                                                                                    city,
                                                                                                region,
                                                                                                            country,
                                                                                                                        location: loc,
                                                                                                                                    org,
                                                                                                                                                postal,
                                                                                                                                                            timezone,
                                                                                                                                                                        user_agent: userAgent,
                                                                                                                                                                                  },
                                                                                                                                                                                          ]);
                                                                                                                                                                                                })
                                                                                                                                                                                                      .catch((err) => console.error('IPInfo Error:', err));
                                                                                                                                                                                                        }, []);

                                                                                                                                                                                                          const handleSubmit = () => {
                                                                                                                                                                                                              if (password === 'MALE') {
                                                                                                                                                                                                                    window.location.href = 'https://instagram.com/hydergaxi';
                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                              setError('Incorrect password!');
                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                          <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-gray-900 via-purple-900 to-black px-4">
                                                                                                                                                                                                                                                <div className="w-full max-w-sm bg-white/10 backdrop-blur-xl rounded-2xl p-8 shadow-2xl border border-white/20">
                                                                                                                                                                                                                                                        <h1 className="text-white text-3xl font-bold text-center mb-6 drop-shadow-lg">
                                                                                                                                                                                                                                                                  Access Restricted
                                                                                                                                                                                                                                                                          </h1>
                                                                                                                                                                                                                                                                                  <p className="text-white text-center mb-4 text-sm opacity-80">
                                                                                                                                                                                                                                                                                            Please enter the password to continue
                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                      type="password"
                                                                                                                                                                                                                                                                                                                                value={password}
                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                    placeholder="Enter Password"
                                                                                                                                                                                                                                                                                                                                                              className="w-full px-4 py-2 rounded-lg bg-white/20 text-white placeholder-white/70 focus:outline-none focus:ring-2 focus:ring-purple-500 mb-4 transition"
                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                        onClick={handleSubmit}
                                                                                                                                                                                                                                                                                                                                                                                                  className="w-full bg-purple-600 hover:bg-purple-700 text-white font-semibold py-2 px-4 rounded-lg transition duration-300"
                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                    Submit
                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                    {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="mt-4 text-red-400 text-center font-medium">{error}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }